[data]
    name = "Steffen Lohbrandt"
    email = "lohbrandt@gmail.com"
    
[edit]
    command = "code"
    args = ["--wait"]
    
[git]
    autoCommit = true
    autoPush = false
    
[hooks.read-source-state.pre]
    command = "brew"
    args = ["bundle", "dump", "--file={{ .chezmoi.sourceDir }}/Brewfile", "--force"]
    
[interpreters.sh]
    command = "bash"
